name: CI

on: [pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.5
      with:
        hugo-version: '0.55.6'
    - name: Hugo Build
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
