name: CI

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.5
      with:
        hugo-version: '0.55.6'
    - name: Hugo Build
      run: hugo --minify
    - uses: actions/upload-artifact@v1
      with:
        name: public
        path: public
