name: staging

on: # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.82.0'
    - name: Hugo Build
      run: hugo --minify --buildDrafts
    - uses: w9jds/firebase-action@master
      with:
          args: deploy --only hosting:pgreze-staging
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
